---
title: "ARFIMA"
author: "Manaswi Mishra"
date: "5/24/2020"
output: rmarkdown::github_document
---

```{r}
#importing data

library(tseries)
library(forecast)
library(Quandl)
Quandl.api_key("UqYbx-p5DwWzyT8AH2c7")
marketpriceUSD<-Quandl("BCHAIN/MKPRU")
```

```{r}
chron <- rev(marketpriceUSD$Value)
c(start = tail(marketpriceUSD$Date, 1), end = head(marketpriceUSD$Date, 1))

```

```{r}
BTC <- ts(chron, start = c(2009, 1, 3), frequency = 365)

# focus on 2017 onwards
train <- window(BTC, start = 2017, end  = 2020)
test <- window(BTC, start = 2020,end = c(2020,30))



```

```{r}
plot(BTC)
plot(train)
plot(test)
```


```{r}
ggseasonplot(train)

ggAcf(train)

gglagplot(train)

hurstexp(train, d = 50, display = TRUE)
#As value of the Hurst estimation is greater than 0.5 this is a long memory TS

```

```{r}
#testing an Arima model
auto.arima(train,trace = TRUE,stepwise = FALSE, max.order = 1000 )
#,lambda = "auto", max.order = 500

```

```{r}
library(arfima)
d <-fracdiff::fracdiff(train) #get the fractional d
arfima.ts<-fracdiff::diffseries(train,d$d) # do the fractional difference
acf(arfima.ts, lag=40)
plot(arfima.ts,type="l")
arfima.model1 <-auto.arima(arfima.ts,stepwise = F,trace = T,lambda = "auto")
arfima.model1

```

```{r}
checkresiduals(arfima.model1)
#Bad results 

```


```{r}
forecast.arfima<-forecast(arfima.model1,h=30)
plot(forecast.arfima)
```

```{r}
accuracy(arfima.model1) 
```
