install.packages("Quandl")
library(Quandl)


Quandl.api_key("UqYbx-p5DwWzyT8AH2c7")

mywalletusers<-Quandl("BCHAIN/MWNUS")
marketpriceUSD<-Quandl("BCHAIN/MKPRU")
extradevolUSD<-Quandl("BCHAIN/TRVOU")
bitdifficulty<-Quandl("BCHAIN/DIFF")
mywallet.nooftran<-Quandl("BCHAIN/MWNTD")
mywallet.voltran<-Quandl("BCHAIN/MWTRV")
avgblksize<-Quandl("BCHAIN/AVBLS")
blkchain.size<-Quandl("BCHAIN/BLCHS")
minersrev<-Quandl("BCHAIN/MIREV")
hashrate<-Quandl("BCHAIN/HRATE")
costpertran<-Quandl("BCHAIN/CPTRA")
costpertranvol<-Quandl("BCHAIN/CPTRV")
esttranvolUSD<-Quandl("BCHAIN/ETRAV")
esttranvol<-Quandl("BCHAIN/ETRAV")
totopvol<-Quandl("BCHAIN/TOUTV")
notranperblk<-Quandl("BCHAIN/NTRBL")
nouniqaddused<-Quandl("BCHAIN/NADDU")
notranexcpopadd<-Quandl("BCHAIN/NTREP")
totnumtran<-Quandl("BCHAIN/NTRAT")
nooftran<-Quandl("BCHAIN/NTRAN")
tranfeeUSD<-Quandl("BCHAIN/TRFUS")
tottranfee<-Quandl("BCHAIN/TRFEE")
marcap<-Quandl("BCHAIN/MKTCP")
totbitcoin<-Quandl("BCHAIN/TOTBC")
mediantranconftime<-Quandl("BCHAIN/ATRCT")
daysdest.yr<-Quandl("BCHAIN/BCDDY")
daysdest.m<-Quandl("BCHAIN/BCDDM")
daysdest.w<-Quandl("BCHAIN/BCDDW")
daysdest<-Quandl("BCHAIN/BCDDE")
daysdest.cum<-Quandl("BCHAIN/BCDDC")
trde.vs.tranvol<-Quandl("BCHAIN/TVTVR")
netwkdefit<-Quandl("BCHAIN/NETDF")
opermargin<-Quandl("BCHAIN/MIOPM")
  
